### ISSUE TITLE
Create boot autoconfig for zk and hazelcast

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-cluster#6]
We should rely on auto-configuration if `spring-cloud-cluster-hazelcast` or/and `spring-cloud-cluster-zookeeper` are in classpath.

We could follow same settings supported by XD for zookeeper:
```
zk:
  namespace: xd
  client:
    connect: node1:2181
```

Should add connection config for hazelcast also. Also possibly add `spring.cloud.cluster.leader.enable` property if leader election auto-config should be disabled.
